### ISSUE TITLE
Node-Red integration 

### ISSUE THREAD

**Issue by Ukhauk** [pimoroni/dot3k#45]
Any suggestions on how to link the display-o-tron to node-red, just thinking it would be great parsing IOT things from node-red to the display.

**Comment by Gadgetoid** [comment]
The "done thing" seems to be to use a very thin NodeJS wrapper to call a Python file that uses the existing Python library to control the hardware

E.G: https://github.com/pimoroni/node-red-nodes/tree/master/blinkt

However, since there's a NodeJS Dot3k library you may be able to leverage that: https://github.com/jorisvervuurt/JVSDisplayOTron

I've been slowly working my way through our products attempting to make NodeJS nodes for them, but haven't had the time to work on it for the last 3 months.
